name: registration_form
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  shared_preferences: ^2.0.15
  email_validator: ^2.0.1

  sizer: ^2.0.15
  responsive_framework: ^0.2.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dev: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/88a5f6155d56f3aa13345dec31a00836.jpg
    - assets/images/1625706047_21-kartinkin-com-p-oboi-v-stile-mangi-krasivie-23.jpg
    - assets/images/bleach-kurosaci-ichigo.jpg
    - assets/images/one-punch-man-saitama-manga-wallpaper-preview.jpg
    - assets/images/XNW16Bi2ZHQ.jpg
    - assets/images/cup_of_coffee.png


